---
title: "Basic Example"
author: "Ruben Cabrera"
date: "2025-10-01"
output: 
  github_document: default
  html_document: default
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_format = "all") })
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Librerias
```{r librerias}

```


# Letura de datos

```{r datos_fuente}
data.vg.raw <- read.csv(here::here("data", "vgsales.csv"))
head(data.vg.raw)
str(data.vg.raw)
```
# Transformación de los datos

```{r}
data.vg.raw$Year <- as.integer(data.vg.raw$Year)
data.vg.raw$Genre <- as.factor(data.vg.raw$Genre)
data.vg.raw$Platform <- as.factor(data.vg.raw$Platform)
data.vg.raw$Publisher <- as.factor(data.vg.raw$Publisher)

```
```{r}
summary(data.vg.raw)
```
```{r}
str(data.vg.raw)
unique(data.vg.raw$Year)
filter(data.vg.raw, Year=="N/A")
```

```{r}
length(unique(data.vg.raw$Name))
```
```{r}
filter(data.vg.raw, Name=="FIFA 15")
```

```{r}
duplicados <- data.vg.raw[duplicated(data.vg.raw$Name), ]
duplicados
```
```{r}
duplicated(data.vg.raw$Name)
```



